version: '3.8'
services:
  music-disc:
    image: hmes98318/music-disc:1.4.2
    container_name: music-disc
    restart: always
    environment:
      TZ: "Asia/Taipei"
      TOKEN: "your_token"
      PREFIX: "+"
      PLAYING: "+help | music"
      EMBEDS_COLOR: "#FFFFFF"
      DEFAULT_VOLUME: 50
      MAX_VOLUME: 100
      AUTO_LEAVE: "true"
      AUTO_LEAVE_COOLDOWN: 5000
      DISPLAY_VOICE_STATE: "true"
      TEXT_QUERY_TYPE: "youtubeSearch"
      URL_QUERY_TYPE: "auto"
      DP_FORCE_YTDL_MOD: "play-dl"
    ports:
      - 33333:33333